###
post http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "guest",
    "name": "Jaime",
    "password": "123",
    "rol": "guest"
}

###
get http://localhost:3001/api/users

###
post http://localhost:3001/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
post http://localhost:3001/api/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NjM4MDg3OTlhZmZhZDY4OWIzYjZhN2EiLCJpYXQiOjE3MTQ5NTMzNjN9.k7_CxJvS2sBTh9JEZQom6kSmz7YmwSmRGvEGiY1is90

{
   "content":{
      "producto":"Producto de prueba",
      "precio":15
   }
}

### 
get http://localhost:3001/api/products